# Generated by Django 6.0.5 on 2026-05-21 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gene",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="GeneVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant", models.CharField(max_length=120)),
                ("chromosome", models.CharField(max_length=8)),
                ("coordinate", models.CharField(max_length=64)),
                ("dbsnp", models.CharField(blank=True, max_length=64)),
                ("hgvs_c", models.CharField(blank=True, max_length=120)),
                ("hgvs_p", models.CharField(blank=True, max_length=120)),
                ("category", models.CharField(blank=True, max_length=80)),
                ("comment", models.TextField(blank=True)),
                ("exon", models.CharField(blank=True, max_length=32)),
                ("zygosity", models.CharField(blank=True, max_length=32)),
                ("gnomad", models.CharField(blank=True, max_length=64)),
                (
                    "gene",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="core.gene",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClinVarGeneVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clinvar_id", models.CharField(max_length=64)),
                ("clinvar_url", models.URLField(max_length=300)),
                (
                    "gene_variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinvar_entry",
                        to="core.genevariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "gene_variants",
                    models.ManyToManyField(
                        blank=True, related_name="patients", to="core.genevariant"
                    ),
                ),
            ],
        ),
    ]
